apiVersion: v1
kind: Service
metadata:
  name: task-manager-api-service
spec:
  type: NodePort
  selector:
    app: task-manager-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
